[package]
name = "loopring_sign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.4"
lazy_static = "1.4.0"
blake2b_simd = "1.0.2"
